server:
  port: 9010

spring:
  application:
    name: lwh-user

eureka:
  client:
    service-url:
      #注册到eureka服务端的地址
      defaultZone: http://localhost:9000/eureka/
  instance:
    #点击具体的微服务，右下角是否显示ip
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    hostname: ${eureka.instance.ip-address}
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}




feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000